namespace SpriteKind {
    export const helper = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.darkGroundNorthEast1, function (sprite, location) {
    story.spriteSayText(sprite, "Turn around, FOLLOW THE ARROWS!!!")
    story.spriteMoveToLocation(animationsprite, 0, 0, -50)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile15`, function (sprite, location) {
    game.showLongText("CODE:0706", DialogLayout.Center)
    pause(1000)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    animationsprite,
    [img`
        ........................
        ....ffffff..............
        ..ffeeeef2f..5..........
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc...5......
        ..ffee44e4dde.5.........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        .......fff..............
        ....fffff2f.............
        ..ffeeeee22ff...........
        .ffeeeeee222ff..........
        .feeeefffeeeef....5.....
        .fffffeee2222ef.5.5.....
        fffe222fffffe2f.5.......
        fffffffffeeefff.....cc..
        fefe44ebbf44eef...ccdc..
        .fee4d4bbfddef..ccddcc..
        ..feee4dddddfeecdddc....
        ...f2222222eeddcdcc..5..
        ...f444445e44ddccc...5..
        ...ffffffffeeee...5..5..
        ...fff...ff.......5.....
        ..................5.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..55...5..
        fffe222ffffe2f..55.555..
        ffffffffeeefff..5..5....
        fefe44ebf44eef..5..5....
        .fee4d4bfddef...........
        ..feee4dddee.c..........
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff......5.55.....
        ..............55..5.....
        ..............5...5.....
        ..............5...5.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef............
        .ffffee2222ef...........
        .fe222ffffe2f.5.........
        fffffffeeefff..5........
        ffe44ebf44eef5..5.......
        fee4d41fddef..5..5......
        .feee4ddddf....5..5.....
        ..fdde444ef...5...5.....
        ..fdde22ccc.55....5.....
        ...eef22cdc......5......
        ...f4444cddc....5.......
        ....fffffcddc..5........
        .....fff..cddc..........
        .....5...5.cdc..........
        ......5.5...cc..........
        ....5..5..5.............
        .....5...5..............
        ......555...............
        ........................
        ........................
        ........................
        `],
    500,
    false
    )
})
function intro () {
    music.play(music.stringPlayable("E B A A E G B F ", 120), music.PlaybackMode.LoopingInBackground)
    animationsprite = sprites.create(img`
        ......ffff..............
        ....fff55fff............
        ...fff5555fff...........
        ..fff555555fff..........
        ..ff555555555f..........
        ..f55ffffff55f..........
        ..ffffddddffff..........
        .ffffdfddfdffff.........
        .fffddfddfddfff.........
        ..fdd1dddd1df...........
        ...fdd1111ddf...........
        ..ddf222222fdd..........
        ..ddf222222fdd..........
        ..ddf888888fdd..........
        .....ffffff.............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
    story.printText("   To begin playing answer the question", 100, 8, 15, 1, story.TextSpeed.Fast)
    pause(500)
    story.printText("Luffy is the main character of what anime?", 100, 8, 15, 1, story.TextSpeed.Normal)
    story.showPlayerChoices("One Piece", "Demon Slayer", "Tokyo Ghoul", "Erased")
    if (story.checkLastAnswer("One Piece")) {
        story.printText("Welcome to the game. You answered the question correctly.", 20, 10, 15, 1, story.TextSpeed.Slow)
        game_calculator(1, 1)
        scene.setBackgroundColor(15)
    }
    if (story.checkLastAnswer("Demon Slayer")) {
        story.printText("Sorry this answer is completely wrong.", 20, 10, 15, 1)
        game.reset()
    } else if (story.checkLastAnswer("Tokyo Ghoul")) {
        story.printText("Nope.", 20, 10, 15, 1)
        game.reset()
    } else if (story.checkLastAnswer("Erased")) {
        story.printText("Try again.", 20, 10, 15, 1)
        game.reset()
    }
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    animationsprite,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 5 5 5 5 5 5 f f . . . . 
        . . f 5 5 5 5 5 5 5 5 5 f . . . 
        . . f 5 5 5 5 5 5 5 5 5 f . . . 
        . f 5 5 5 5 5 5 5 5 5 5 f . . . 
        . f 5 5 f f f f 5 5 5 5 f . . . 
        . f f f b b b f f f f f f f . . 
        . f 5 5 d d f b b d d b f f . . 
        . . f 5 d d f 1 d d d b b f . . 
        . . . f d d d d d b b b f . . . 
        . . . f 2 2 2 2 b b f f . . . . 
        . . . f 2 2 2 d d d d . . . . . 
        . . . f 2 2 2 d d d d . . . . . 
        . . . f 8 8 8 8 d d f . . . . . 
        . . . . 8 8 8 8 8 8 . . . . . . 
        . . . . . . 8 8 8 . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 5 5 5 5 5 5 f f . . . . 
        . . f 5 5 5 5 5 5 5 5 f f . . . 
        . . f 5 5 5 5 5 5 5 5 5 f . . . 
        . f 5 5 5 5 5 5 5 5 5 5 f . . . 
        . f 5 5 f f f f 5 5 5 5 f . . . 
        . f f f b b b f f f f f f f . . 
        . f b b d d f b b d d b f f . . 
        . . f b d d f 1 d d d b b f . . 
        . . . f d d d b b b b b f . . . 
        . . . f 2 2 2 2 d d f . . . . . 
        . . . f 2 2 2 2 d d f . . . . . 
        . . 8 8 8 8 8 8 8 8 8 8 . . . . 
        . . 8 8 8 8 8 8 8 8 8 8 . . . . 
        . . . 8 8 8 . . . 8 8 . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    500,
    false
    )
})
function game_calculator (level: number, challenge: number) {
    let list: tiles.WorldMap[] = []
    game.splash("Choose a level to start on")
    pause(100)
    game.splash(game.askForNumber("", 1))
    listchallenge = [
    img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,
    img`
        . . . . . . . . . . . . . . . . 
        . . b b 1 1 1 1 1 1 1 b . . . . 
        . . b b 2 b 1 1 1 b 2 1 b . . . 
        . . b b 2 b 1 1 1 b 2 1 b . . . 
        . b b b 2 b 1 1 1 b 2 1 b . . . 
        . b b f f f 1 1 b f f f 1 b . . 
        . b b b 2 b 1 1 1 b 2 1 1 b . . 
        . . b b 2 b 2 2 2 b 2 1 1 b . . 
        . . b b 2 b 2 2 2 b 2 1 1 b . . 
        . . b b 2 2 2 b 2 2 2 1 1 . . . 
        . . b b 1 1 1 1 1 1 1 1 1 . . . 
        . . b b b 2 2 2 2 2 2 1 1 . . . 
        . . . b 1 1 1 1 1 1 1 1 1 . . . 
        . . . . b b b b b b b b b . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . b 5 b . . . 
        . . . . . . . . . b 5 b . . . . 
        . . . . . . b b b b b b . . . . 
        . . . . . b b 5 5 5 5 5 b . . . 
        . . . . b b 5 d 1 f 5 d 4 c . . 
        . . . . b 5 5 1 f f d d 4 4 4 b 
        . . . . b 5 5 d f b 4 4 4 4 b . 
        . . . b d 5 5 5 5 4 4 4 4 b . . 
        . . b d d 5 5 5 5 5 5 5 5 b . . 
        . b d d d d 5 5 5 5 5 5 5 5 b . 
        b d d d b b b 5 5 5 5 5 5 5 b . 
        c d d b 5 5 d c 5 5 5 5 5 5 b . 
        c b b d 5 d c d 5 5 5 5 5 5 b . 
        . b 5 5 b c d d 5 5 5 5 5 d b . 
        b b c c c d d d d 5 5 5 b b . . 
        . . . c c c c c c c c b b . . . 
        `,
    img`
        . . . . f f f f f . . . . . . . 
        . . . f e e e e e f . . . . . . 
        . . f d d d d e e e f . . . . . 
        . c d f d d f d e e f f . . . . 
        . c d f d d f d e e d d f . . . 
        c d e e d d d d e e b d c . . . 
        c d d d d c d d e e b d c . . . 
        c c c c c d d e e e f c . . . . 
        . f d d d d e e e f f . . . . . 
        . . f f f f f e e e e f . . . . 
        . . . . f f e e e e e e f . f f 
        . . . f e e f e e f e e f . e f 
        . . f e e f e e f e e e f . e f 
        . f b d f d b f b b f e f f e f 
        . f d d f d d f d d b e f f f f 
        . . f f f f f f f f f f f f f . 
        `
    ]
    if (level == 0) {
        tiles.loadMap(list[0])
    }
    if (level == 1 && false) {
        tiles.loadMap(list[1])
    }
    if (level == 2 && false) {
        tiles.loadMap(list[2])
    }
    if (level == 3 && false) {
        tiles.loadMap(list[3])
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    animationsprite,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f f 5 5 5 5 f f . . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . f f 5 5 5 5 5 5 5 5 5 f . . 
        . . f 5 5 5 5 5 5 5 5 5 5 f . . 
        . . f f f f f f f f f f f f . . 
        . f f f f f f f f f f f f f f . 
        . f f f f f f f f f f f f f f . 
        . . f d d d f f d f f d d f . . 
        . . . f d d d d d d d d f . . . 
        . . d d f 2 2 2 2 2 2 f d d . . 
        . . d d f 2 2 2 2 2 2 f d d . . 
        . . d d f 8 8 8 8 8 8 f d d . . 
        . . . . . 8 8 8 8 8 8 . . . . . 
        . . . . . 8 8 . . 8 8 . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f 5 5 5 5 f f . . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . f f 5 5 5 5 5 5 5 5 5 f . . 
        . . f 5 5 5 5 5 5 5 5 5 5 f . . 
        . . f f 5 5 5 5 5 5 5 f f f . . 
        . . f 5 5 f f f f 5 f f f f . . 
        . f f f f f f f f f f f f f f . 
        . f f f f f f f f f f d d f f . 
        . . . f d d d d d d d d f . . . 
        . . . d 2 2 2 2 2 2 2 2 d d . . 
        . . . d 2 2 2 2 2 2 d d d d . . 
        . . . d 8 8 8 8 8 8 d d d . . . 
        . . . . 8 8 8 . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f 5 5 5 5 f f . . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . f 5 5 5 5 5 5 5 5 5 5 f . . 
        . . f 5 5 5 5 5 5 5 5 5 5 f . . 
        . f f 5 f f f f f f f f f f f . 
        . f f f f f f f f f f f f f f . 
        . . f f f d d f f d f f f f . . 
        . . . f d d d d d d d d f . . . 
        . . d d f f f f f f f f d d . . 
        . . d d f 2 2 2 2 2 2 f d d . . 
        . . d d f 2 2 2 2 2 2 f d d . . 
        . . . . . 8 8 8 8 8 8 . . . . . 
        . . . . . 8 8 . . 8 8 . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f 5 5 5 5 f f . . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . . f 5 5 5 5 5 5 5 5 f . . . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . f 5 5 5 5 5 5 5 5 5 5 f . . 
        . . f f f 5 5 5 5 5 5 f f f . . 
        . . f f f f f f f f f f f f . . 
        . f f f f f f f f f f f f f f . 
        . f f f d d f f d d f d d f f . 
        . . . f d d d d d d d d f . . . 
        . . d d 2 2 2 2 2 2 2 2 d . . . 
        . . d d d d 2 2 2 2 2 2 d . . . 
        . . . d d d 8 8 8 8 8 8 d . . . 
        . . . . . . . . . 8 8 8 . . . . 
        `],
    500,
    false
    )
})
let listchallenge: Image[] = []
let animationsprite: Sprite = null
intro()
info.setScore(0)
animationsprite = sprites.create(img`
    ......ffff..............
    ....fff55fff............
    ...fff5555fff...........
    ..fff555555fff..........
    ..ff555555555f..........
    ..f55ffffff55f..........
    ..ffffddddffff..........
    .ffffdfddfdffff.........
    .fffddfddfddfff.........
    ..fdd1dddd1df...........
    ...fdd1111ddf...........
    ..ddf222222fdd..........
    ..ddf222222fdd..........
    ..ddf888888fdd..........
    .....ffffff.............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(animationsprite, 100, 100)
scene.cameraFollowSprite(animationsprite)
let projectile = sprites.createProjectileFromSide(img`
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 d 4 c . . 
    . . . . b 5 5 1 f f d d 4 4 4 b 
    . . . . b 5 5 d f b 4 4 4 4 b . 
    . . . b d 5 5 5 5 4 4 4 4 b . . 
    . . b d d 5 5 5 5 5 5 5 5 b . . 
    . b d d d d 5 5 5 5 5 5 5 5 b . 
    b d d d b b b 5 5 5 5 5 5 5 b . 
    c d d b 5 5 d c 5 5 5 5 5 5 b . 
    c b b d 5 d c d 5 5 5 5 5 5 b . 
    . b 5 5 b c d d 5 5 5 5 5 d b . 
    b b c c c d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `, 50, 50)
let mySprite = sprites.create(img`
    ........................
    ........................
    ........6999999.........
    ........6666666.........
    .......66ffff6..........
    .......6fffff6..........
    .......66fff66..........
    .......66fff66..........
    .......66fff66..........
    .....669996699966.......
    .....966666666666.......
    .....996666666999.......
    ....6699996699966.......
    ....66666ffff66666......
    ...666669ffff96666......
    ...666669ffff96666......
    ..6666999ffff996666.....
    ..6669966ffff696666.....
    ..6699666ffff699966.....
    ...66666fffff666966.....
    ...666666ffff6666.......
    ........6fff66..........
    ........66666...........
    ........................
    `, SpriteKind.helper)
let levelmap = [
tiles.createMap(tilemap`level1`),
tiles.createMap(tilemap`level11`),
tiles.createMap(tilemap`level3`),
tiles.createMap(tilemap`level12`)
]
game.onUpdateInterval(500, function () {
	
})
